import { jsPDF } from 'jspdf';
import { AssessmentResult } from '../types';
import { PersonalityResult } from '../types/personality';

/**
 * Generates a PDF summary report for RIASEC Holland Code Assessment Results
 */
export function generateRiasecPdf(result: AssessmentResult, userName: string = 'Student'): Buffer {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Header Banner
  doc.setFillColor(30, 58, 138); // Royal Blue #1E3A8A
  doc.rect(0, 0, 210, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Bausalty (Bousalty) - Career Blueprint', 15, 18);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Holland Code (RIASEC) College Major Assessment', 15, 28);

  // Student Info Box
  doc.setTextColor(58, 47, 33); // Ink #3a2f21
  doc.setFillColor(251, 246, 234); // Paper #fbf6ea
  doc.rect(15, 46, 180, 22, 'F');
  doc.setDrawColor(58, 47, 33);
  doc.setLineWidth(0.5);
  doc.rect(15, 46, 180, 22, 'S');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Student Name: ${userName}`, 20, 54);
  doc.text(`Holland Code: ${result.topCode}`, 20, 62);
  doc.text(`Date Completed: ${new Date(result.completedAt).toLocaleDateString()}`, 110, 54);
  doc.text(`Primary Trait: ${result.primaryType}`, 110, 62);

  // Scores Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. RIASEC Normalized Scores (0 - 100%)', 15, 80);

  const categories = ['R', 'I', 'A', 'S', 'E', 'C'] as const;
  const labels: Record<string, string> = {
    R: 'Realistic (Practical / Hands-on)',
    I: 'Investigative (Analytical / Scientific)',
    A: 'Artistic (Creative / Visionary)',
    S: 'Social (Helping / Educational)',
    E: 'Enterprising (Leadership / Business)',
    C: 'Conventional (Organized / Data)',
  };

  let yPos = 90;
  categories.forEach((cat) => {
    const score = result.normalizedScores[cat] || 0;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${cat} - ${labels[cat]}: ${score}%`, 20, yPos);

    // Draw score bar
    doc.setFillColor(243, 234, 217);
    doc.rect(110, yPos - 4, 80, 5, 'F');
    doc.setFillColor(13, 148, 136); // Teal #0d9488
    doc.rect(110, yPos - 4, (score / 100) * 80, 5, 'F');

    yPos += 10;
  });

  // Top Recommended Majors
  yPos += 5;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Top Recommended Saudi University Majors', 15, yPos);
  yPos += 8;

  result.matchingMajors.slice(0, 5).forEach((major, idx) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`${idx + 1}. ${major.nameEn} (${major.riasecCode}) - ${major.matchScore}% Match`, 20, yPos);
    
    yPos += 5;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Careers: ${major.sampleCareersEn.slice(0, 3).join(', ')}`, 25, yPos);

    yPos += 5;
    doc.text(`Saudi Universities: ${major.saudiUniversitiesEn.slice(0, 3).join(', ')}`, 25, yPos);

    yPos += 8;
  });

  // Footer Note
  doc.setFontSize(8);
  doc.setTextColor(138, 122, 95);
  doc.text('Generated by Bausalty - Tahseen AI Group | Saudi Vision 2030 Career Alignment Platform', 15, 285);

  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}

/**
 * Generates a PDF summary report for 16Personalities Assessment Results
 */
export function generatePersonalityPdf(result: PersonalityResult, userName: string = 'Student'): Buffer {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Header Banner
  doc.setFillColor(124, 58, 237); // AI Purple #7c3aed
  doc.rect(0, 0, 210, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Bausalty - 16Personalities Profile', 15, 18);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Myers-Briggs Archetype & Learning Style Summary', 15, 28);

  // Student Info Box
  doc.setTextColor(58, 47, 33);
  doc.setFillColor(251, 246, 234);
  doc.rect(15, 46, 180, 22, 'F');
  doc.setDrawColor(58, 47, 33);
  doc.setLineWidth(0.5);
  doc.rect(15, 46, 180, 22, 'S');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Student Name: ${userName}`, 20, 54);
  doc.text(`MBTI Archetype: ${result.code} - ${result.archetype.titleEn}`, 20, 62);
  doc.text(`Date Completed: ${new Date(result.completedAt).toLocaleDateString()}`, 120, 54);

  // Trait Breakdown
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Personality Dimensions Breakdown', 15, 80);

  let yPos = 90;
  const dims = [
    { label: 'Extraversion (E) vs Introversion (I)', score1: result.percentages.EI.E, score2: result.percentages.EI.I },
    { label: 'Sensing (S) vs Intuition (N)', score1: result.percentages.SN.S, score2: result.percentages.SN.N },
    { label: 'Thinking (T) vs Feeling (F)', score1: result.percentages.TF.T, score2: result.percentages.TF.F },
    { label: 'Judging (J) vs Perceiving (P)', score1: result.percentages.JP.J, score2: result.percentages.JP.P },
  ];

  dims.forEach((d) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${d.label}: ${d.score1}% / ${d.score2}%`, 20, yPos);

    doc.setFillColor(243, 234, 217);
    doc.rect(110, yPos - 4, 80, 5, 'F');
    doc.setFillColor(124, 58, 237);
    doc.rect(110, yPos - 4, (d.score1 / 100) * 80, 5, 'F');

    yPos += 10;
  });

  // Strengths & Learning Style
  yPos += 5;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Core Strengths & Learning Style', 15, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Strengths: ${result.archetype.strengthsEn.join(', ')}`, 20, yPos);
  yPos += 8;

  doc.text(`Learning Style: ${result.archetype.learningStyleEn}`, 20, yPos, { maxWidth: 170 });
  yPos += 15;

  // Aligned Majors
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('3. Aligned Saudi College Majors', 15, yPos);
  yPos += 8;

  result.archetype.linkedMajorsEn.forEach((m, idx) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`• ${m} (Holland Code: ${result.archetype.linkedRiasecCodes[idx] || 'IRC'})`, 20, yPos);
    yPos += 6;
  });

  // Footer Note
  doc.setFontSize(8);
  doc.setTextColor(138, 122, 95);
  doc.text('Generated by Bausalty - Tahseen AI Group | Saudi Vision 2030 Career Alignment Platform', 15, 285);

  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}
